name: Update market data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Fetch latest market data
        run: python scripts/fetch_market_data.py

      - name: Commit and push if data changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json data/history
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update market data"
            git push
          fi
